improve output and functions

diff --git a/bin/dfboot b/bin/dfboot
--- a/bin/dfboot
+++ b/bin/dfboot
@@ -1,89 +1,168 @@
 #!/bin/bash
 
 # TODO
-# - !!! check what runs first: clone or dfbstrap?
-# - .bashrc and .profile ?
 # - .ssh/{config,known_hosts}
 # - SSH Keys generation and copy
 # - /etc/hosts
-# - colorize df_exit_status
-# - case system detection
-# - break into IDEMPOTENT functions - respect ORDER:
-# - • sudo -v
-#   • prep (repo)
-#   • df_get_pkgs (min sw)
-#   • df_env (shell, plugins, editor)
-#   • code (dev frameworks)
+# - colorize bdb_exit_status
+# - user interaction
+# - --silent / --verbose flags
 
-### Provide --help flag
+### Prepare for execution
+
+# Force exit in case of error
+set -e
+
+# Call error handler before exiting
+trap "bdb_handle_error" EXIT
+
+# Provide --help flag
 if [ ${#@} -ne 0 ] && [ "${@#"--help"}" = "" ]; then
-    printf -- '...help...\n';
-    exit 0;
-fi;
+    printf -- '...help...\n'
+    exit 0
+fi
 
-### Define variables and functions
+### Define variables
+
+# Output colors
+ESC_SEQ="\x1b["
+COL_RESET=$ESC_SEQ"39;49;00m"
+COL_RED=$ESC_SEQ"31;01m"
+COL_GREEN=$ESC_SEQ"32;01m"
+COL_YELLOW=$ESC_SEQ"33;01m"
+COL_BLUE=$ESC_SEQ"34;01m"
+COL_MAGENTA=$ESC_SEQ"35;01m"
+COL_CYAN=$ESC_SEQ"36;01m"
+COL_WHITE=$ESC_SEQ"97;01m"
 
 # Local paths
-BARE_DIR=$HOME/.dfbare              # git dir name for bare repo
-BAKP_DIR=$HOME/.dfbackup            # backup dir for pre-existing dotfiles
-ANTG_DIR=$HOME/.antigen             # antigen plugins dir
-VNDL_DIR=$HOME/.vim/bundle          # Vundle plugins dir
-APT_PKGS=$HOME/.dfconf/apt-packages # required APT packages
-BRW_PKGS=$HOME/.dfconf/Brewfile     # required brew packages
+BARE_DIR="$HOME/.dfbare"     # git dir name for bare repo
+BAKP_DIR="$HOME/.dfbackup"   # backup dir for pre-existing dotfiles
+ANTG_DIR="$HOME/.antigen"    # antigen plugins dir
+VNDL_DIR="$HOME/.vim/bundle" # Vundle plugins dir
 
 # Remote URLs
-REPO_URL='https://github.com/norville/dotfiles.git'
-BREW_URL='https://raw.githubusercontent.com/Homebrew/install/master/install'
-VNDL_URL='https://github.com/VundleVim/Vundle.vim.git'
+REPO_URL="https://github.com/norville/dotfiles.git"
+BREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
+VNDL_URL="https://github.com/VundleVim/Vundle.vim.git"
 
-# Check last exit status and print message
-function df_exit_status() {
+# Required packages
+BASE_PKG="vim git wget curl zsh"
+UBNT_PKG="$BASE_PKG python3-pip"
+BREW_PKG="$HOME/.dfconf/Brewfile"
 
-    if [[ $? != 0 ]]; then
-        # Print error message and exit
-        echo "Error $1"
-        exit 2
-    else
-        # Print success message
-        echo "Done $1"
+### Define functions
+
+function bdb_handle_error() {
+
+    ERR_CODE=$?
+    if [[ $ERR_CODE != 0 ]]; then
+        printf -- "Error ${ERR_CODE} has occurred."
+        # TODO - handle exit codes and cleanup
+        printf -- "\nExiting with error code ${ERR_CODE}.\n"
+        exit ${ERR_CODE}
     fi
 
 }
 
-function df_handle_error() {
+# Check last exit status and print outcome message
+function bdb_exit_status() {
 
-    ERR_CODE=$?
-    printf -- "Error ${ERR_CODE} has occurred."
-    # ... cleanup code ...
-    printf -- "\nExiting with error code ${ERR_CODE}.\n"
-    exit ${ERROR_CODE}
+    if [[ $? != 0 ]]; then
+        # Print error message and exit
+        echo -e "\n$COL_RED|xxx| ERROR $1 $COL_RESET"
+    else
+        # Print success message
+        echo -e "$COL_GREEN|+++| DONE $1 $COL_RESET"
+    fi
 
 }
 
-function df_message() {
+# Print info message - NEWLINE
+function bdb_info() {
 
-    echo $1
+    echo -e "\n$COL_WHITE|BDB| $1 $COL_RESET"
+
+}
+
+# Print run message - NO NEWLINE
+function bdb_run() {
+
+    echo -en "\n$COL_MAGENTA|***| $1 ...$COL_RESET"
+
+}
+
+# Print outcome message - INLINE
+function bdb_outcome() {
+
+    echo -e "$COL_BLUE $1 $COL_RESET"
+
+}
+
+# Print message before command - NEWLINE
+function bdb_action() {
+
+    echo -e "\n$COL_CYAN|>>>| $1 $COL_RESET"
+
+}
+
+# Check the system and prepare for bootstrap
+function bdb_check_sys() {
+
+    # Detect system
+    bdb_run "Running BDB on a "
+    if [[ $(uname -s) == 'Darwin' ]]; then
+        export MACOS=true
+        bdb_outcome "macOS system"
+    else
+        export MACOS=false
+        bdb_outcome "Linux system"
+    fi
+
+    # Get admin privileges
+    #TODO no newline after password input
+    bdb_run "Getting admin privileges"
+    sudo -v
+
+    # Check basic packages
+    bdb_run "Checking for basic packages"
+    if [[ $MACOS == true && ! $(which brew) ]]; then
+
+        # Init macOS base sys
+        bdb_outcome "installing basic macOS packages"
+        /usr/bin/ruby -e "$(curl -fsSL $BREW_URL)"
+        bdb_exit_status "installing Homebrew"
+        bdb_action "Installing basic packages"
+        brew install $BASE_PKG
+        bdb_exit_status "installing macOS basic packages"
+
+    elif [[ $MACOS == false && ! $(which git) ]]; then
+
+        # Init Linux base sys
+        bdb_outcome "installing basic Linux packages"
+        sudo apt update && sudo apt install -y $BASE_PKG
+        bdb_exit_status "installing basic Linux packages"
+
+    else
+        bdb_outcome "<$BASE_PKG> installed"
+    fi
+
+    bdb_info "System ready"
 
 }
 
 # Automatically run git against the bare repo in $HOME
-function dfconf {
+function dfconf() {
+
     # /usr/bin/git --git-dir=<git-bare-dir> --work-tree=<dotfiles-dir>
     /usr/bin/git --git-dir=$BARE_DIR --work-tree=$HOME $@
+
 }
 
 # Clone dotfiles into a local bare repo
-function df_clone_bare {
+function bdb_clone_repo() {
 
-    df_message "Checking local bare repo"
-
-    # If git is not installed exit now
-    if [[ ! $(which git) ]]; then
-        df_message "Git not installed, getting it via APT"
-        #TODO call portable app to install only git
-        sudo apt-get install -y git
-        df_exit_status "installing git"
-    fi
+    bdb_run "Looking for dotfiles"
 
     # Set bare repo dir
     mkdir -p $BARE_DIR
@@ -91,109 +170,119 @@ function df_clone_bare {
     # If bare repo is not already set
     if [[ ! $(git --git-dir=$BARE_DIR rev-parse --is-bare-repository) ]]; then
 
+        bdb_action "Dotfiles not found, cloning remote repo into a bare one"
+
         # Clone remote repo into bare repo
         #git clone --bare $REPO_URL $BARE_DIR           # Clone master branch
-        git clone --bare -b bare $REPO_URL $BARE_DIR    # Clone specifc branch
-        df_exit_status "cloning bare repo into $BARE_DIR"
+        git clone --bare -b bare $REPO_URL $BARE_DIR # Clone specifc branch
+        bdb_exit_status "cloning bare repo into $BARE_DIR"
 
         # Checkout bare repo
+        bdb_action "Checking out dotfiles repo"
         dfconf checkout
         # If checkout fails
         if [[ $? != 0 ]]; then
             # Create backup dir
+            bdb_action "Backing up overlapping dotfiles"
             mkdir -p $BAKP_DIR
             # Move pre-existing dotfiles to $BAKP_DIR
             dfconf checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} $BAKP_DIR/{}
             dfconf checkout
         fi
-        df_exit_status "checking out bare repo"
+        bdb_exit_status "checking out bare repo"
 
         # Config bare repo to ignore untracked files
         dfconf config status.showUntrackedFiles no
 
     fi
 
-    df_message "Bare repo ready"
-}
+    #TODO handle remote pull if repo is set
 
-# Get last version of Homebrew and install a bundle of packages if given
-function df_brew() {
+    bdb_info "Dotfiles ready"
 
-    # Check if bundle is valid
-    if [[ ! -f $1 ]]; then
-        # bundle not valid
-        exit 1
-        #TODO handle error message
-    else
-
-        # Install Homebrew if missing
-        if [[ ! $(which brew) ]]; then
-            /usr/bin/ruby -e "$(curl -fsSL $BREW_URL)"
-            df_exit_status "installing Homebrew"
-        fi
-
-        # Install bundle if not up to date
-        if [[ ! $(brew bundle check --file=$1) ]]; then
-            brew bundle -v --file=$1
-            df_exit_status "installing bundle $1"
-        fi
-
-        # Remove extra packages if requested
-        if [[ $(brew bundle cleanup --file=$1) ]]; then
-            read -r -p "Found extra packages, do you want to uninstall them? [y|n] " response
-            if [[ $response =~ (yes|y|Y) ]]; then
-                brew bundle cleanup --file=$1 --force
-                df_exit_status "removing extra packages"
-            fi
-        fi
-
-        # Update Homebrew
-        brew update --force
-        df_exit_status "updating Homebrew"
-
-        # Upgrade all formulae
-        brew upgrade
-        df_exit_status "upgrading Homebrew formulae"
-
-        # Upgrade all casks
-        brew cask upgrade #--greedy
-        df_exit_status "upgrading Homebrew caks"
-
-        # Do some maintenance
-        brew cleanup
-        brew doctor
-
-    fi
 }
 
 # Install or update required packages
-function df_get_pkgs() {
+function bdb_get_packages() {
 
-    #TODO modify logic:
-    # - no args (default) = install list of packages
-    # - 1+ args = install given packages
-
-    df_message "Getting required packages"
+    bdb_run "Getting required packages"
 
     # Detect system
-    if [[ $MACOS ]]; then
+    if [[ $MACOS == true ]]; then
 
         # System is macOS
+        bdb_outcome "for macOS"
 
-        df_brew $BRW_PKGS
+        # Check if bundle is valid
+        if [[ -f $BREW_PKG && -s $BREW_PKG ]]; then
+
+            # Update Homebrew
+            bdb_action "Updating Homebrew"
+            brew update --force
+            bdb_exit_status "updating Homebrew"
+
+            # Install bundle if not up to date
+            if [[ ! $(brew bundle check --file=$BREW_PKG) ]]; then
+
+                bdb_action "Installing required formulae"
+                brew bundle -v --file=$BREW_PKG
+                bdb_exit_status "installing required formulae"
+
+            fi
+
+            # Look for extra packages
+            if [[ $(brew bundle cleanup --file=$BREW_PKG) ]]; then
+
+                # Extra packages installed
+                bdb_run "Found extra formulae installed"
+                read -r -p "do you want to uninstall them? [y|n] " response
+                if [[ $response =~ (yes|y|Y) ]]; then
+
+                    # Delete extra packages
+                    brew bundle cleanup --file=$BREW_PKG --force
+                    bdb_exit_status "removing extra formulae"
+
+                else
+
+                    # Upgrade all formulae
+                    bdb_action "Upgrading all formulae"
+                    brew upgrade
+                    bdb_exit_status "upgrading Homebrew formulae"
+
+                    # Upgrade all casks
+                    bdb_action "Upgrading all casks"
+                    brew cask upgrade #--greedy
+                    bdb_exit_status "upgrading Homebrew caks"
+
+                fi
+            fi
+
+            # Do some maintenance
+            brew cleanup
+            brew doctor
+
+        else
+
+            # bundle not valid
+            bdb_info "Invalid bundle. Exiting..."
+            exit 3
+
+        fi
 
         # Update PIP base packages
+        bdb_action "Updating PIP packages"
         pip3 install -U pip setuptools wheel
-        df_exit_status "updating PIP packages"
+        bdb_exit_status "updating PIP packages"
 
     else
 
         # System is Linux
+        bdb_outcome "for Ubuntu"
 
         # Install or update required packages via APT
-        # TODO make it distro indipendent: support yum and arch pkgs
-        xargs -a $APT_PKGS sudo apt-get install -y
-        df_exit_status "installing required packages in $APT_PKGS"
+        bdb_action "Installing APT packages: <$UBNT_PKG>"
+        sudo apt update && sudo apt install -y $UBNT_PKG
+        bdb_exit_status "installing APT packages"
 
         # Cleanup
         sudo apt autoremove
@@ -202,84 +291,78 @@ function df_get_pkgs() {
     fi
 
     # Install/update antigen
+    bdb_action "Installing Antigen"
     if [[ -d $ANTG_DIR ]]; then
         rm -rf $ANTG_DIR
     fi
     mkdir -p $ANTG_DIR
-    curl -L git.io/antigen > $ANTG_DIR/antigen.zsh
+    curl -L git.io/antigen >$ANTG_DIR/antigen.zsh
+    bdb_exit_status "installing Antigen"
 
-    #df_message "Required packages ready"
+    bdb_info "Required packages ready"
+
 }
 
 # Configure the environment
-function df_env() {
+function bdb_set_env() {
 
-    df_message "Configuring this environment"
-
-    df_message "Configuring the shell"
+    bdb_info "Configuring this environment"
 
     # Ensure ZSH is the login shell
+    bdb_run "Configuring the shell"
     ZSH_PATH=$(which zsh)
     if [[ $SHELL != $ZSH_PATH ]]; then
 
         # Set ZSH as login shell
+        bdb_action "Setting ZSH as login shell"
         echo $ZSH_PATH | sudo tee -a /etc/shells
         sudo chsh -s $ZSH_PATH $USER
-        df_exit_status "setting ZSH as login shell"
+        bdb_exit_status "setting ZSH as login shell"
 
     fi
-
-    df_message "Configuring the editor"
 
     # Install or update Vundle and required plugins
+    bdb_run "Configuring the editor"
     if [[ ! -d $VNDL_DIR/Vundle.vim ]]; then
-        # Download Vundle
-        git clone $VNDL_URL $VNDL_DIR/Vundle.vim
-        df_exit_status "installing Vundle"
-    fi
 
+        # Install Vundle
+        bdb_action "Installing Vundle - VIM plugin manager"
+        git clone $VNDL_URL $VNDL_DIR/Vundle.vim
+        bdb_exit_status "installing Vundle"
+
+    fi
     # Update Vundle and required plugins
-    vim -i NONE -c VundleUpdate -c quitall > /dev/null 2>&1
-    df_exit_status "updating Vundle plugins"
+    bdb_action "Updating VIM plugins via Vundle"
+    vim -i NONE -c VundleUpdate -c quitall >/dev/null 2>&1
+    bdb_exit_status "updating Vundle plugins"
 
     # TODO
     # - LNX set gruvbox theme for terminal
     # - LNX restore preferences
     # - MAC restore preferences (Mackup / Mathias)
 
-    df_message "Environment ready"
+    bdb_info "Environment ready"
+
 }
 
 ### Bootstrap begin
+bdb_info "Welcome to Bassa Dofiles Bootstrapper (BDB)!"
 
-# Force exit in case of error
-set -e
+# Checkthe system
+bdb_check_sys
 
-# Call error handler before exiting
-#trap "df_handle_error" EXIT
+# Prepare bare repo
+bdb_clone_repo
 
-# Detect system
-if [[ $(uname -s) == 'Darwin' ]]; then
-    export MACOS=true
-fi
+# Install or update required software
+bdb_get_packages
 
-# Get admin privileges
-sudo -v
-
-### Prepare bare repo
-df_clone_bare
-
-### Install or update required software
-df_get_pkgs
-
-### Configure environment
-df_env
+# Configure environment
+bdb_set_env
 
 ### Bootstrap end
+bdb_info "All done!"
 
-# TODO countdown to reboot
-
-### Exit in style
+# Exit in style
 printf -- '\n'
 exit 0
-
