improve documentation

diff --git a/bin/dfboot b/bin/dfboot
--- a/bin/dfboot
+++ b/bin/dfboot
@@ -27,19 +27,19 @@ fi
 ### Define constants
 
 ESC_SEQ="\x1b["
-RST_COL="${ESC_SEQ}39;49;00m"   # reset
-RED_COL="${ESC_SEQ}31;01m"      # red
-GRN_COL="${ESC_SEQ}32;01m"      # green
-YLW_COL="${ESC_SEQ}33;01m"      # yellow
-BLU_COL="${ESC_SEQ}34;01m"      # blue
-MGN_COL="${ESC_SEQ}35;01m"      # magenta
-CYN_COL="${ESC_SEQ}36;01m"      # cyan
-WHT_COL="${ESC_SEQ}97;01m"      # white
+RST_COL="${ESC_SEQ}39;49;00m" # reset
+RED_COL="${ESC_SEQ}31;01m"    # red
+GRN_COL="${ESC_SEQ}32;01m"    # green
+YLW_COL="${ESC_SEQ}33;01m"    # yellow
+BLU_COL="${ESC_SEQ}34;01m"    # blue
+MGN_COL="${ESC_SEQ}35;01m"    # magenta
+CYN_COL="${ESC_SEQ}36;01m"    # cyan
+WHT_COL="${ESC_SEQ}97;01m"    # white
 
-FRESH=""                        # true = fresh install
-DISTRO=""                       # unix distro name
-SYSTEM=""                       # os name
-BARE_DIR="${HOME}/.dfbare"      # git bare repo dir
+FRESH=""                   # true = fresh install
+DISTRO=""                  # unix distro name
+SYSTEM=""                  # os name
+BARE_DIR="${HOME}/.dfbare" # git bare repo dir
 #CURR_CMD=$(basename $0)         # current running command
 
 ### Define functions
@@ -118,74 +118,88 @@ bdb_do_sys() {
     ## Detect local system
     bdb_run "Local system is "
     LSB_NAME="/etc/os-release"
+    # If /etc/os-release exists
     if [[ -f "${LSB_NAME}" ]]; then
+
+        # System is Linux, then get os name
         SYSTEM="$(grep -e '^ID=' ${LSB_NAME} | cut -d '=' -f 2)"
+
     else
+
+        # /etc/os-release is missing, assume macos
         SYSTEM="macos"
+
     fi
     case "${SYSTEM}" in
-        ubuntu|debian|raspbian)
-            DISTRO="debian"
+
+    ubuntu | debian | raspbian)
+        DISTRO="debian"
         ;;
-        manjaro*|arch)
-            DISTRO="arch"
+
+    manjaro* | arch)
+        DISTRO="arch"
         ;;
-        macos)
-            DISTRO="darwin"
+
+    macos)
+        DISTRO="darwin"
         ;;
-        *)
-            DISTRO="unknown"
+
+    *)
+        DISTRO="unknown"
         ;;
+
     esac
     bdb_outcome "${SYSTEM} (${DISTRO})"
 
-    ## Prepare local system
+    ## Prepare local system: update packages cache and install requirements
     case "${DISTRO}" in
 
-        arch)
-            bdb_command "Updating Pacman"
-            sudo pacman -Syy
-            bdb_exit_status "updating Pacman"
+    arch)
+        bdb_command "Updating Pacman"
+        sudo pacman -Syy
+        bdb_exit_status "updating Pacman"
         ;;
 
-        darwin)
-            # If brew is missing
-            if ! type brew &>/dev/null; then
+    darwin)
+        # If brew is missing
+        if ! type brew &>/dev/null; then
 
-                # Install homebrew
-                BREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
-                bdb_command "Installing Homebrew"
-                /usr/bin/ruby -e "$(curl -fsSL ${BREW_URL})"
-                bdb_exit_status "installing Homebrew"
+            # Install homebrew
+            BREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
+            bdb_command "Installing Homebrew"
+            /usr/bin/ruby -e "$(curl -fsSL ${BREW_URL})"
+            bdb_exit_status "installing Homebrew"
 
-            else
+        else
 
-                # Update homebrew
-                bdb_command "Updating Homebrew"
-                brew update
-                bdb_exit_status "updating Homebrew"
+            # Update homebrew
+            bdb_command "Updating Homebrew"
+            brew update
+            bdb_exit_status "updating Homebrew"
 
-            fi
+        fi
         ;;
 
-        debian)
-            bdb_command "Updating APT"
-            sudo apt-get update
-            bdb_exit_status "updating APT"
+    debian)
+        bdb_command "Updating APT"
+        sudo apt-get update
+        bdb_exit_status "updating APT"
 
-            # If git is missing
-            if ! type git &>/dev/null; then
+        # If git is missing
+        if ! type git &>/dev/null; then
 
-                #Install git
-                bdb_command "Installing git"
-                sudo apt-get install -y git
-                bdb_exit_status "installing git"
+            #Install git
+            bdb_command "Installing git"
+            sudo apt-get install -y git
+            bdb_exit_status "installing git"
 
-            fi
+        fi
         ;;
 
-        *) bdb_exit_status "Cannot detect local system. Exiting..."
-            exit 1
+    *)
+        bdb_exit_status "Cannot detect local system. Exiting..."
+        #TODO improve error handling
+        exit 1
         ;;
     esac
 
@@ -222,7 +236,7 @@ bdb_do_repo() {
         # Clone remote repo into bare repo
         REPO_URL="https://github.com/norville/dotfiles.git"
         bdb_command "Cloning dotfiles into a bare repo"
-        git clone --bare ${REPO_URL} ${BARE_DIR}                    # Clone master branch
+        git clone --bare ${REPO_URL} ${BARE_DIR} # Clone master branch
         #git clone --bare -b <git-branch> ${REPO_URL} ${BARE_DIR}   # Clone specifc branch
         bdb_exit_status "cloning dotfiles into <${BARE_DIR}>"
 
@@ -249,7 +263,7 @@ bdb_do_repo() {
         # Config bare repo to ignore untracked files
         dfconf config status.showUntrackedFiles no
 
-        # Set remote Github via ssh 
+        # Set remote Github via ssh
         dfconf remote set-url origin git@github.com:norville/dotfiles.git
 
     else
@@ -274,78 +288,79 @@ bdb_do_apps() {
     # Detect system
     case "${DISTRO}" in
 
-        macos)  # System is macOS
+    macos) # System is macOS
 
-            # Install brew bundles
-            BREW_PKG="${HOME}/.dfconf.d/brewfile"
-            bdb_command "Installing required formulae from <${BREW_PKG}>"
-            brew bundle install --file=${BREW_PKG}
-            bdb_exit_status "installing required formulae"
+        # Install brew bundles
+        BREW_PKG="${HOME}/.dfconf.d/brewfile"
+        bdb_command "Installing required formulae from <${BREW_PKG}>"
+        brew bundle install --file=${BREW_PKG}
+        bdb_exit_status "installing required formulae"
 
-            # If extra formulae are installed
-            if [[ "$(brew bundle cleanup --file=${BREW_PKG})" ]]; then
+        # If extra formulae are installed
+        if [[ "$(brew bundle cleanup --file=${BREW_PKG})" ]]; then
 
-                bdb_run "Do you want to uninstall extra formulae? [y|n] "
-                read -r -n 1 response
-                if [[ "${response}" =~ (y|Y) ]]; then
+            bdb_run "Do you want to uninstall extra formulae? [y|n] "
+            read -r -n 1 response
+            if [[ "${response}" =~ (y|Y) ]]; then
 
-                    # Delete extra formulae
-                    bdb_command "Removing extra formulae"
-                    brew bundle cleanup --file=${BREW_PKG} --force
-                    bdb_exit_status "removing extra formulae"
+                # Delete extra formulae
+                bdb_command "Removing extra formulae"
+                brew bundle cleanup --file=${BREW_PKG} --force
+                bdb_exit_status "removing extra formulae"
 
-                else
+            else
 
-                    # Upgrade all formulae
-                    bdb_command "Upgrading all formulae"
-                    brew upgrade
-                    bdb_exit_status "upgrading all formulae"
-
-                fi
+                # Upgrade all formulae
+                bdb_command "Upgrading all formulae"
+                brew upgrade
+                bdb_exit_status "upgrading all formulae"
 
             fi
 
-            # Cleanup
-            bdb_command "Cleaning Homebrew"
-            brew cleanup
-            bdb_exit_status "cleaning Homebrew"
+        fi
+
+        # Cleanup
+        bdb_command "Cleaning Homebrew"
+        brew cleanup
+        bdb_exit_status "cleaning Homebrew"
 
         ;;
 
-        debian) # System is debian
+    debian) # System is debian
 
-            # Install or update required packages via APT
-            DEBN_PKG="vim git wget curl zsh"
-            bdb_command "Installing APT packages: <${DEBN_PKG}>"
-            sudo apt-get install -y ${DEBN_PKG}
-            bdb_exit_status "installing APT packages"
+        # Install or update required packages via APT
+        DEBN_PKG="vim git wget curl zsh"
+        bdb_command "Installing APT packages: <${DEBN_PKG}>"
+        sudo apt-get install -y ${DEBN_PKG}
+        bdb_exit_status "installing APT packages"
 
-            # Cleanup
-            bdb_command "Cleaning APT"
-            sudo apt autoremove
-            sudo apt autoclean
-            bdb_exit_status "cleaning APT"
-
-        ;;
-
-        arch) # System is arch
-
-            # Install or update required packages via Pacman
-            ARCH_PKG="vim git wget curl zsh tilix"
-            bdb_command "Installing Arch packages: <${ARCH_PKG}>"
-            sudo pacman --noconfirm --needed -S ${ARCH_PKG}
-            bdb_exit_status "installing Arch packages"
-
-            # Cleanup
-            bdb_command "Cleaning Pacman cache"
-            sudo pacman --noconfirm -Scc
-            bdb_exit_status "cleaning Pacman cache"
+        # Cleanup
+        bdb_command "Cleaning APT"
+        sudo apt autoremove
+        sudo apt autoclean
+        bdb_exit_status "cleaning APT"
 
         ;;
 
-        *) # Distro not detected
-            bdb_info "Cannot detect your system! Exiting..."
-            bdb_handle_error 10
+    arch) # System is arch
+
+        # Install or update required packages via Pacman
+        ARCH_PKG="vim git wget curl zsh tilix"
+        bdb_command "Installing Arch packages: <${ARCH_PKG}>"
+        sudo pacman --noconfirm --needed -S ${ARCH_PKG}
+        bdb_exit_status "installing Arch packages"
+
+        # Cleanup
+        bdb_command "Cleaning Pacman cache"
+        sudo pacman --noconfirm -Scc
+        bdb_exit_status "cleaning Pacman cache"
+
+        ;;
+
+    *) # Distro not detected
+        bdb_info "Unknown system: ${DISTRO}. Exiting..."
+        # TODO improve error handling
+        bdb_handle_error 10
         ;;
 
     esac
@@ -410,72 +425,72 @@ bdb_do_cli() {
 
     case "${DISTRO}" in
 
-        arch)
-            bdb_run "Installing Nerd fonts for p10k"
+    arch)
+        bdb_run "Installing Nerd fonts for p10k"
 
-            # Install nerd fonts for p10k
-            FONT_DIR="${HOME}/.local/share/fonts"
-            FURA_FNT="Fura Mono Regular Nerd Font.otf"
-            MSLO_FNT="Meslo LG S Regular Nerd Font.ttf"
-            FURA_URL="https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraMono/Regular/complete/Fura%20Mono%20Regular%20Nerd%20Font%20Complete.otf"
-            MSLO_URL="https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf"
+        # Install nerd fonts for p10k
+        FONT_DIR="${HOME}/.local/share/fonts"
+        FURA_FNT="Fura Mono Regular Nerd Font.otf"
+        MSLO_FNT="Meslo LG S Regular Nerd Font.ttf"
+        FURA_URL="https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraMono/Regular/complete/Fura%20Mono%20Regular%20Nerd%20Font%20Complete.otf"
+        MSLO_URL="https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf"
 
-            mkdir -p ${FONT_DIR}
-            bdb_command "Installing Fura Mono"
-            curl -fLo "${FONT_DIR}/${FURA_FNT}" "${FURA_URL}"
-            bdb_exit_status "installing Fura Mono"
-            bdb_command "Installing Meslo"
-            curl -fLo "${FONT_DIR}/${MSLO_FNT}" "${MSLO_URL}"
-            bdb_exit_status "installing Meslo"
-            bdb_command "Updating fonts"
-            fc-cache -f
-            bdb_exit_status "updating fonts"
+        mkdir -p ${FONT_DIR}
+        bdb_command "Installing Fura Mono"
+        curl -fLo "${FONT_DIR}/${FURA_FNT}" "${FURA_URL}"
+        bdb_exit_status "installing Fura Mono"
+        bdb_command "Installing Meslo"
+        curl -fLo "${FONT_DIR}/${MSLO_FNT}" "${MSLO_URL}"
+        bdb_exit_status "installing Meslo"
+        bdb_command "Updating fonts"
+        fc-cache -f
+        bdb_exit_status "updating fonts"
 
-            # Set up tilix
-            bdb_command "Installing Gruvbox theme for Tilix"
-            git clone https://github.com/MichaelThessel/tilix-gruvbox.git
-            cd tilix-gruvbox
-            sudo cp gruvbox-* /usr/share/tilix/schemes
-            cd ..
-            rm -rf tilix-gruvbox
-            bdb_exit_status "installing Gruvbox theme for Tilix"
+        # Set up tilix
+        bdb_command "Installing Gruvbox theme for Tilix"
+        git clone https://github.com/MichaelThessel/tilix-gruvbox.git
+        cd tilix-gruvbox
+        sudo cp gruvbox-* /usr/share/tilix/schemes
+        cd ..
+        rm -rf tilix-gruvbox
+        bdb_exit_status "installing Gruvbox theme for Tilix"
 
-            #TODO GNU Stow or mackup
-
-        ;;
-
-        macos)
-
-            # If this is a fresh install
-            if [[ "${FRESH}" ]]; then
-
-                # Set macos defaults
-                bdb_command "Restoring macOS preferences"
-                MAC_DEF="${HOME}/bin/macos_defaults"
-                [[ "${MAC_DEF}" ]] && source "${MAC_DEF}"
-                bdb_exit_status "restoring macOS preferences"
-
-                # Run mackup
-                bdb_command "Restoring App preferences"
-                type mackup &>/dev/null && mackup restore
-                bdb_exit_status "restoring App preferences"
-
-            fi
-
-            # Restore VSCode extensions
-            CODE_EXT="${HOME}/.dfconf.d/vscode-ext"
-            # If no extensions installed and extensions file exists
-            if [[ ! $(code --list-extensions) && -f "${CODE_EXT}" ]]; then
-
-                bdb_command "Installing VSCode extensions"
-                cat "${CODE_EXT}" | xargs -n 1 code --install-extension
-                bdb_exit_status "installing VSCode extensions"
-
-            fi
+        #TODO GNU Stow or mackup
 
         ;;
 
-        *) # Nothing to do
+    macos)
+
+        # If this is a fresh install
+        if [[ "${FRESH}" ]]; then
+
+            # Set macos defaults
+            bdb_command "Restoring macOS preferences"
+            MAC_DEF="${HOME}/bin/macos_defaults"
+            [[ "${MAC_DEF}" ]] && source "${MAC_DEF}"
+            bdb_exit_status "restoring macOS preferences"
+
+            # Run mackup
+            bdb_command "Restoring App preferences"
+            type mackup &>/dev/null && mackup restore
+            bdb_exit_status "restoring App preferences"
+
+        fi
+
+        # Restore VSCode extensions
+        CODE_EXT="${HOME}/.dfconf.d/vscode-ext"
+        # If no extensions installed and extensions file exists
+        if [[ ! $(code --list-extensions) && -f "${CODE_EXT}" ]]; then
+
+            bdb_command "Installing VSCode extensions"
+            cat "${CODE_EXT}" | xargs -n 1 code --install-extension
+            bdb_exit_status "installing VSCode extensions"
+
+        fi
+
+        ;;
+
+    *) # Nothing to do
         ;;
 
     esac
@@ -501,4 +516,3 @@ bdb_info "All done!"
 # Exit in style
 printf -- '\n'
 exit 0
-
